// <auto-generated />
using System;
using IT008.Q13_Project___fromScratch.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT008.Q13_Project___fromScratch.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118183415_AddDisplayCountsToDeck")]
    partial class AddDisplayCountsToDeck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("IT008.Q13_Project___fromScratch.Models.Card", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackAudioPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrontAudioPath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("IT008.Q13_Project___fromScratch.Models.CardProgress", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("EaseFactor")
                        .HasPrecision(18, 6)
                        .HasColumnType("REAL");

                    b.Property<double>("Interval")
                        .HasPrecision(18, 6)
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.HasIndex("DueDate");

                    b.ToTable("CardProgresses", (string)null);
                });

            modelBuilder.Entity("IT008.Q13_Project___fromScratch.Models.Deck", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DueCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LearnCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Decks", (string)null);
                });

            modelBuilder.Entity("IT008.Q13_Project___fromScratch.Models.Card", b =>
                {
                    b.HasOne("IT008.Q13_Project___fromScratch.Models.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("IT008.Q13_Project___fromScratch.Models.CardProgress", b =>
                {
                    b.HasOne("IT008.Q13_Project___fromScratch.Models.Card", "Card")
                        .WithOne("Progress")
                        .HasForeignKey("IT008.Q13_Project___fromScratch.Models.CardProgress", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("IT008.Q13_Project___fromScratch.Models.Card", b =>
                {
                    b.Navigation("Progress")
                        .IsRequired();
                });

            modelBuilder.Entity("IT008.Q13_Project___fromScratch.Models.Deck", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
